version: "3"

services:
  postgres:
    image: clkao/postgres-plv8:12-2
    ports:
      - 5432:5432
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
